# Generated by Django 4.0 on 2022-06-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Invoice', '0002_alter_client_address_line1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('unit', models.CharField(blank=True, choices=[('1', 'ml'), ('2', 'pcs'), ('3', 'ltr'), ('4', 'units'), ('5', 'kg'), ('6', 'g')], max_length=10, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
