# Generated by Django 4.0 on 2022-06-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0003_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='user',
            new_name='users',
        ),
    ]
