# Generated by Django 4.0 on 2022-06-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0004_rename_user_inventory_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(blank=True, choices=[('ml', 'ml'), ('pcs', 'pcs'), ('ltr', 'ltr'), ('unit', 'unit'), ('kg', 'kg'), ('g', 'g')], max_length=10, null=True),
        ),
    ]
